<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RND-BASE-A" ignored="0" name="Default test" tests="2" failures="1" timestamp="2023-10-11T06:44:06 PDT" time="1.814" errors="0">
  <testcase name="postequipmentControllerv4" time="1.505" classname="Private.equipmentControllerV4">
    <failure type="java.lang.AssertionError" message="{
    &amp;quot;Equipment&amp;quot;: {
        &amp;quot;Success&amp;quot;: false,
        &amp;quot;Data&amp;quot;: null,
        &amp;quot;Messages&amp;quot;: [
            {
                &amp;quot;Enabled&amp;quot;: 1,
                &amp;quot;Info&amp;quot;: &amp;quot;Could not create equipment. Equipment Id (EQUIP0101) already exist.&amp;quot;,
                &amp;quot;Level&amp;quot;: 3
            }
        ]
    }
}">
      <![CDATA[java.lang.AssertionError: {
    "Equipment": {
        "Success": false,
        "Data": null,
        "Messages": [
            {
                "Enabled": 1,
                "Info": "Could not create equipment. Equipment Id (EQUIP0101) already exist.",
                "Level": 3
            }
        ]
    }
}
at org.testng.Assert.fail(Assert.java:99)
at Private.equipmentControllerV4.postequipmentControllerv4(equipmentControllerV4.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- postequipmentControllerv4 -->
  <testcase name="postequipmentControllerv4Error" time="0.225" classname="Private.equipmentControllerV4"/>
</testsuite> <!-- Default test -->
